services:
  postgres_db:
    image: postgres:15-alpine
    container_name: postgres_db
    env_file:
      - ./backend/.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  authentication:
    build:
      context: ./backend
      dockerfile: Authentication/Dockerfile
    container_name: authentication_service
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - postgres_db
    restart: unless-stopped

  dashboard:
    build:
      context: ./backend
      dockerfile: Dashboard/Dockerfile
    container_name: dashboard_service
    env_file:
      - ./backend/.env
    ports:
      - "8001:8001"
    depends_on:
      - postgres_db
      - authentication
    restart: unless-stopped

  patient:
    build:
      context: ./backend
      dockerfile: PatientService/Dockerfile
    container_name: patient_service
    env_file:
      - ./backend/.env
    ports:
      - "8004:8004"
    depends_on:
      - postgres_db
      - authentication
    restart: unless-stopped

  vitals:
    build:
      context: ./backend
      dockerfile: VitalsService/Dockerfile
    container_name: vitals_service
    env_file:
      - ./backend/.env
    ports:
      - "8005:8005"
    depends_on:
      - postgres_db
      - authentication
    restart: unless-stopped

  prescription:
    build:
      context: ./backend
      dockerfile: PrescriptionService/Dockerfile
    container_name: prescription_service
    env_file:
      - ./backend/.env
    ports:
      - "8006:8006"
    depends_on:
      - postgres_db
      - authentication
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    env_file:
      - ./frontend/.env
    ports:
      - "3000:80"
    depends_on:
      - authentication
      - dashboard
      - patient
      - vitals
      - prescription
    restart: unless-stopped

volumes:
  pgdata: