PROGNOSIS_DRUG_MAP = {
    'Fungal Infection': ['Antifungals'],
    'Allergy': ['Antihistamines'],
    'GERD': ['Proton Pump Inhibitors', 'Antacids'],
    'Chronic Cholestasis': ['Ursodeoxycholic Acid'],
    'Drug Reaction': ['Corticosteroids', 'Antihistamines'],
    'Peptic Ulcer Disease': ['Proton Pump Inhibitors', 'Antibiotics', 'Antacids'],
    'AIDS': ['Antiretrovirals'],
    'Diabetes': ['Insulin', 'Metformin'],
    'Gastroenteritis': ['Rehydration Salts', 'Antibiotics'],
    'Bronchial Asthma': ['Bronchodilators', 'Corticosteroids'],
    'Hypertension': ['ACE Inhibitors', 'Beta Blockers'],
    'Migraine': ['Triptans', 'NSAIDs'],
    'Cervical Spondylosis': ['NSAIDs', 'Muscle Relaxants'],
    'Paralysis (brain hemorrhage)': ['Anticoagulants', 'Rehabilitation Therapy'],
    'Jaundice': ['Supportive Care'],
    'Malaria': ['Antimalarials'],
    'Chickenpox': ['Antivirals', 'Antihistamines'],
    'Dengue': ['Paracetamol', 'Fluids'],
    'Typhoid': ['Antibiotics'],
    'Hepatitis A': ['Supportive Care'],
    'Hepatitis B': ['Antivirals'],
    'Hepatitis C': ['Antivirals'],
    'Hepatitis D': ['Interferon'],
    'Hepatitis E': ['Supportive Care'],
    'Alcoholic Hepatitis': ['Steroids', 'Abstinence Support'],
    'Tuberculosis': ['Antitubercular Drugs'],
    'Common Cold': ['Decongestants', 'Antihistamines'],
    'Pneumonia': ['Antibiotics'],
    'Dimorphic Hemmorhoids (piles)': ['Laxatives', 'Anti-inflammatories'],
    'Heart Attack': ['Aspirin', 'Nitroglycerin', 'Beta Blockers'],
    'Varicose Veins': ['Pain Relievers', 'Compression Therapy'],
    'Hypothyroidism': ['Levothyroxine'],
    'Hyperthyroidism': ['Antithyroid Drugs'],
    'Hypoglycemia': ['Glucose Tablets', 'Dextrose'],
    'Osteoarthritis': ['NSAIDs'],
    'Arthritis': ['NSAIDs', 'DMARDs'],
    'Vertigo': ['Antihistamines', 'Meclizine'],
    'Acne': ['Topical Retinoids', 'Antibiotics'],
    'Urinary Tract Infection': ['Antibiotics'],
    'Psoriasis': ['Topical Corticosteroids'],
    'Impetigo': ['Topical Antibiotics', 'Oral Antibiotics'],
}

all_prescriptions = sorted(set(drug for lst in PROGNOSIS_DRUG_MAP.values() for drug in lst))
PRESCRIPTION_LIST = [{"id": i, "name": name} for i, name in enumerate(all_prescriptions)]
PRESCRIPTION_ID_TO_NAME = {i: name for i, name in enumerate(all_prescriptions)}
PRESCRIPTION_NAME_TO_ID = {name: i for i, name in enumerate(all_prescriptions)}